In [52]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

from scipy.linalg import lu

In [23]:
np.random.seed(42)

x = np.array([2, 5, 5, 1, 2]) 
A0 = np.random.randint(-5, 5, (5,5))

print("A =\n", A)
print()

b0 = A0 @ x

print("b =", b)

A =
 [[ 1 -2  2 -1  1]
 [ 4 -3  1  2 -1]
 [-2  2  2 -3  0]
 [-1 -4  2  0 -4]
 [-1 -5  4  0  3]]

b = [  3  -2  13 -20  -1]


In [38]:
# метод Гаусса

A = A0.copy()
b = b0.copy()

for i in range(b.shape[0]):
    k = A[:, i] / A[i, i]
    k[i] = 0

    A = A - A[i, :] * k[:, None]
    b = b - k * b[i]
    
with np.printoptions(precision=3):
    print(A)

[[ 1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  5.000e+00 -8.882e-16  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  3.200e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  2.625e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.179e+01]]


In [46]:
P, L, U = lu(A0)
print(P)
print(L)
print(U)

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
[[ 1.          0.          0.          0.          0.        ]
 [-0.25        1.          0.          0.          0.        ]
 [-0.5        -0.08695652  1.          0.          0.        ]
 [ 0.25        0.2173913   0.28787879  1.          0.        ]
 [-0.25        0.82608696 -0.43939394  0.73913043  1.        ]]
[[ 4.         -3.          1.          2.         -1.        ]
 [ 0.         -5.75        4.25        0.5         2.75      ]
 [ 0.          0.          2.86956522 -1.95652174 -0.26086957]
 [ 0.          0.          0.         -1.04545455  0.72727273]
 [ 0.          0.          0.          0.         -7.17391304]]


In [56]:
A = A0.copy()
b = b0.copy()
x = x.copy()

H = np.diag([0.1] * 5)
x = np.array([1] * 5).T


def f(A, x, b):
    return A @ x - b


for k in range(10):
    x = x - H @ f(A, x, b)
    
print(x)

[[0.1 0.  0.  0.  0. ]
 [0.  0.1 0.  0.  0. ]
 [0.  0.  0.1 0.  0. ]
 [0.  0.  0.  0.1 0. ]
 [0.  0.  0.  0.  0.1]]
[  8.13966619  33.97173145 -17.33001028   8.94715633  28.71864975]
